<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>.:: SISTEMA::.</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
[var.js;htmlconv=no;noerr]
<script type="text/javascript" src="../js/validation.js?"></script>
<style type="text/css">
.classname {
	-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
	-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
	box-shadow:inset 0px 1px 0px 0px #ffffff;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );
	background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');
	background-color:#ededed;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #dcdcdc;
	display:inline-block;
	color:#777777;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #ffffff;
}.classname:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );
	background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');
	background-color:#dfdfdf;
}.classname:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>



</head>

<body >
<div  style=" position:fixed;  width:250px; border-radius:10px; margin-left:10px; top:20px; "> 
<img border="0" src="../imagenes/logo.jpg" width="300" height="300">
</div>
<fieldset  style=" background-color:#BFE2FD; position:fixed;  width:600px; border-radius:10px; margin-left:250px; top:120px; " >
<legend >pacientealdia.com</legend>
<form name="form_ingresar" id="form_ingresar" action="javascript:validar();">

<table border="0" align="center" >

	<tr>
		<td><strong><label><font color="grey">Usuario</font></label></strong></td>
		<td align="left"><input type="text" name="usuarioTx" id="usuarioTx" maxlength="16" size="40"    /></td>
	</tr>
	<tr>
		<td><strong><label><font color="grey">Clave</font></label></strong></td>
		<td align="left"><input type="password" name="clavetx" id="clavetx" maxlength="40" size="40"   /> </td>
	</tr>
	<tr>
		<td colspan="2" align="center">
		<input	type="submit" class="classname" value="Iniciar seción" name="btn_ingresar" id="btn_ingresar" />
		</td>
	</tr>
	<tr>
		<td colspan="2" align="right">
		<strong ><a href="../controladores/registrar_usuario.php"><font color="grey">Nuevo usuario</font></a></strong>
		</td>
	</tr>	
	
	</table>

	</form>
</fieldset>

<div style="position:fixed; top:300px;  margin-left:250px; width:630px;text-align:justify; text-justify:inter-word;">
<font face="verdana" size="2" color="black">
Es un sistema desarrollado con tecnología Web, orientada a profesionales del área médica que les permite acceder a la 
información de sus pacientes, las 24 horas del día, los 7 días de semana, durante 365 días al año de manera ininterrumpida a
través de cualquier dispositivo fijo y móvil  con acceso a Internet. Permite consultar, ingresar y actualizar  los 
historiales de los pacientes de manera segura sin preocuparse por el mantenimiento de su computador o dispositivos de acceso,
 a demás de garantizar el respaldo de la información. Genera automáticamente los informes médicos y tratamientos en formato 
 de archivos (pdf ), los cuales puede ser impresos  y almacenados en cualquier momento.
</font>
<p align="center">
<font  face="verdana" size="1" color="grey" >Este site ha sido desarrollado por pacientealdia.com. Derechos reservados</font></p>
</div>
</body>
</html>
